services:
  - type: web
    name: unigest-backend
    runtime: node
    rootDir: Backend
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: JWT_EXPIRES_IN
        value: 7d
      - key: FRONTEND_URL
        value: https://unigest-55t5.onrender.com  # ← remplacez par votre URL frontend
      - key: DATABASE_URL
        sync: false   # valeur saisie manuellement dans le dashboard Render
      - key: PORT
        value: 5000
